## Basic Configuration
baseurl = "https://pilgrim-lifestyle.jp/"
languageCode = "en-us"

title = "Pilgrim Style"
theme = "triple-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

summarylength = 50

paginate = 5

## Site Settings
[params]
    author = "YasuhiroKimesawa"
    title = "Pilgrim Style"
    description = "..."
    #authorimage = "images/author.png"
    dateformat = "Jan 2, 2006"
    mainSections = ["post"]

    # sidebar, copyright & license
    logoimage = "images/logo-1.png"
    copyright = "YasuhiroKimesawa"
    since = 2019
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

[params.giscus]
    # repo = "author/repo"
    # repoID = "<id>"
    # category = "Announcements"
    # categoryID = "<id>"
    mapping = "pathname"
    strict = "1"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "light"
    lang = "en"
    loading = "lazy"

## Social Accounts
[params.social]
    github = "YasuhiroKimesawa"
    instagram = "yasuhirokimesawa"
    #linkedin = "<username>"
    twitter = "pilgrim_reds"
    facebook = "pilgrim.ericclapton"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    #email = "your-email@example.com"
    #mastodon = "<username>"
    #threads = "@<username>"
    # gravatar = "your-email@example.com"
    # pgpkey = "<path-to-your-key-in-/static>"

## Main Menu
[[menu.main]]
    name = "Blogs"
    weight = 100
    identifier = "blog"
    url = "/blog/"
#[[menu.main]]
#    name = "Portfolio"
#    identifier = "portfolio"
#    weight = 200
#    url = "/portfolio/"
#[[menu.main]]
#    name = "Icons"
#    identifier = "icons"
#    weight = 250
#    url = "/icons/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
