name: Deploy Github Pages

on:
  push:
    branches:
      - hugo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    - name: Clone submodule
      run: git submodule update --init --recursive
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.1
      with:
        # The Hugo version to download (if necessary) and use. Example: 0.58.2
        hugo-version:  0.60.1 # optional, default is latest
        # Download (if necessary) and use Hugo extended version. Example: true
        extended: true # optional, default is false
    - name: Build Hugo
      run: hugo -v
    - name: Add CNAME
      run: echo pilgrim-lifestyle.jp > ./public/CNAME
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
